### PR TITLE
Middleware

### PR DESCRIPTION
**Pull request by bartvanhoutte**
Based on the middleware implementation in kriswallsmith/Buzz. Only supports intercepting the Request so far.

### CODE REVIEW

**Comment by bartvanhoutte** [comment]
I've cloned master and the test that fails in this PR fails on master as well. I can't figure out on how to make it work at the moment. However, I was able to fix PHP 5.3 compatibility after some tinkering in Docker.

**Comment by clue** [comment]
@bartvanhoutte Thanks for looking into this, this looks like a good starting point :+1: 

Let me look into the build error first, this seems to be unrelated to your PR (and also affects #142).

**Comment by jcchavezs** [comment]
@clue @bartvanhoutte any idea on when/how to restart this? Maybe rebasing is first good step?

**Comment by clue** [comment]
Thanks for your patience!

The unrelated build error has been fixed via #145 in the meantime, so the build should now be able to pass. A rebase may be required to trigger a new build.

I still think this feature makes perfect sense and I think this PR is a good starting point. It doesn't currently contain any tests and very little documentation, so this is definitely something that needs to be worked out.

From an API perspective, I like the `withMiddleware()` approach (this is in line with the new options API planned in #154). I'm not sure I like the `MiddlewareInterface` because I'd rather KISS. Perhaps we can use a simple callable definition like we're doing in https://github.com/reactphp/http#middleware? Among others, this also allows working with both the outgoing request and incoming response objects. 

Another thing that has yet to be worked out is how this interferes with existing options like redirects, timeouts and compression (#49). It's my understanding this should be handled "internally", i.e. the middleware will only see the outgoing request and the redirected response in return when redirects are used (can be disabled of course).

What do you think?

**Comment by clue** [comment]
Again thanks for bringing this up! I have to close this one as per #177 now that future development will focus on https://github.com/reactphp/http instead. If you feel this makes sense to port over, please file a new PR over in the new repo and I'm happy to help review this :+1:

**Comment by jcchavezs** [comment]
Good to hear? Could we please transfer the issue instead? Or at least copy
it?

søn. 12. jul. 2020, 23:17 skrev Christian Lück <notifications@github.com>:

**Comment by clue** [comment]
New PRs are very much welcome! :+1:

**Comment by jcchavezs** [comment]
I am sorry. I somehow thought there was an issue for this. I might create one.

**Pull request closed without merging**
